# Generated by Django 6.0.4 on 2026-05-10 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0233_device_render_config_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('vlan_id', models.IntegerField()),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.device')),
            ],
            options={
                'unique_together': {('device', 'vlan_id')},
            },
        ),
    ]
